name: mi_card
description: A new Flutter application.


analyzer:
  enable-experiment:
    - non-nullable
environment:
  sdk: ">=2.13.0-68.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^3.0.1


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true

  assets:
    - images/ibrahim.jpg
